// 🤖 AUTO-GENERATED - DO NOT EDIT
// Generated by: scripts/codegen.ts

import { config as clientsConfig } from '@/modules/clients/routes.config';
import { config as devConfig } from '@/modules/dev/routes.config';
import { config as engagementContractsConfig } from '@/modules/engagement-contracts/routes.config';
import { config as invoicesConfig } from '@/modules/invoices/routes.config';
import { config as mattersConfig } from '@/modules/matters/routes.config';
import { config as onboardingConfig } from '@/modules/onboarding/routes.config';
import { config as payoutsConfig } from '@/modules/payouts/routes.config';
import { config as practiceConfig } from '@/modules/practice/routes.config';
import { config as practiceClientIntakesConfig } from '@/modules/practice-client-intakes/routes.config';
import { config as preferencesConfig } from '@/modules/preferences/routes.config';
import { config as publicConfig } from '@/modules/public/routes.config';
import { config as stripeConfig } from '@/modules/stripe/routes.config';
import { config as subscriptionsConfig } from '@/modules/subscriptions/routes.config';
import { config as trustConfig } from '@/modules/trust/routes.config';
import { config as webhooksConfig } from '@/modules/webhooks/routes.config';
import { config as workerEventsConfig } from '@/modules/worker-events/routes.config';

export const CONFIG_REGISTRY = [
  { name: 'clients', config: clientsConfig },
  { name: 'dev', config: devConfig },
  { name: 'engagement-contracts', config: engagementContractsConfig },
  { name: 'invoices', config: invoicesConfig },
  { name: 'matters', config: mattersConfig },
  { name: 'onboarding', config: onboardingConfig },
  { name: 'payouts', config: payoutsConfig },
  { name: 'practice', config: practiceConfig },
  { name: 'practice-client-intakes', config: practiceClientIntakesConfig },
  { name: 'preferences', config: preferencesConfig },
  { name: 'public', config: publicConfig },
  { name: 'stripe', config: stripeConfig },
  { name: 'subscriptions', config: subscriptionsConfig },
  { name: 'trust', config: trustConfig },
  { name: 'webhooks', config: webhooksConfig },
  { name: 'worker-events', config: workerEventsConfig }
] as const;
