// 🤖 AUTO-GENERATED - DO NOT EDIT
// Generated by: scripts/codegen.ts

import clientsHttp from '@/modules/clients/http';
import devHttp from '@/modules/dev/http';
import engagementContractsHttp from '@/modules/engagement-contracts/http';
import invoicesHttp from '@/modules/invoices/http';
import mattersHttp from '@/modules/matters/http';
import onboardingHttp from '@/modules/onboarding/http';
import payoutsHttp from '@/modules/payouts/http';
import practiceHttp from '@/modules/practice/http';
import practiceClientIntakesHttp from '@/modules/practice-client-intakes/http';
import preferencesHttp from '@/modules/preferences/http';
import publicHttp from '@/modules/public/http';
import stripeHttp from '@/modules/stripe/http';
import subscriptionsHttp from '@/modules/subscriptions/http';
import trustHttp from '@/modules/trust/http';
import webhooksHttp from '@/modules/webhooks/http';
import workerEventsHttp from '@/modules/worker-events/http';

export const MODULE_REGISTRY = [
  { name: 'clients', http: clientsHttp },
  { name: 'dev', http: devHttp },
  { name: 'engagement-contracts', http: engagementContractsHttp },
  { name: 'invoices', http: invoicesHttp },
  { name: 'matters', http: mattersHttp },
  { name: 'onboarding', http: onboardingHttp },
  { name: 'payouts', http: payoutsHttp },
  { name: 'practice', http: practiceHttp },
  { name: 'practice-client-intakes', http: practiceClientIntakesHttp },
  { name: 'preferences', http: preferencesHttp },
  { name: 'public', http: publicHttp },
  { name: 'stripe', http: stripeHttp },
  { name: 'subscriptions', http: subscriptionsHttp },
  { name: 'trust', http: trustHttp },
  { name: 'webhooks', http: webhooksHttp },
  { name: 'worker-events', http: workerEventsHttp }
] as const;

export type ModuleName = typeof MODULE_REGISTRY[number]['name'];
