// 🤖 AUTO-GENERATED - DO NOT EDIT
// Generated by: scripts/build.ts
// Last updated: 2026-01-10T09:45:13.745Z

import onboardingHttp from '@/modules/onboarding/http';
import practiceHttp from '@/modules/practice/http';
import practiceClientIntakesHttp from '@/modules/practice-client-intakes/http';
import preferencesHttp from '@/modules/preferences/http';
import publicHttp from '@/modules/public/http';
import subscriptionsHttp from '@/modules/subscriptions/http';
import webhooksHttp from '@/modules/webhooks/http';

export const MODULE_REGISTRY = [
  { name: 'onboarding', http: onboardingHttp },
  { name: 'practice', http: practiceHttp },
  { name: 'practice-client-intakes', http: practiceClientIntakesHttp },
  { name: 'preferences', http: preferencesHttp },
  { name: 'public', http: publicHttp },
  { name: 'subscriptions', http: subscriptionsHttp },
  { name: 'webhooks', http: webhooksHttp }
] as const;

export type ModuleName = typeof MODULE_REGISTRY[number]['name'];
