/**
 * AUTO-GENERATED FILE - DO NOT EDIT MANUALLY
 *
 * This file is automatically generated by: pnpm run sync:listeners
 * It imports and registers all event listeners discovered in modules and shared directories.
 *
 * To add a new listener:
 * 1. Create a listeners.ts file in your module or a *.listeners.ts in shared/events/listeners
 * 2. Export a function named register{ModuleName}Listeners()
 * 3. Run: pnpm run sync:listeners (or pnpm run build)
 *
 * Last updated: 2026-01-25T14:54:35.189Z
 */

import { getLogger } from '@logtape/logtape';
import { registerAnalyticsListeners } from '@/shared/events/listeners/analytics.listeners';
import { registerAuthListeners } from '@/modules/auth/listeners';
import { registerClientsListeners } from '@/modules/clients/listeners';
import { registerMattersListeners } from '@/modules/matters/listeners';
import { registerOnboardingListeners } from '@/modules/onboarding/listeners';
import { registerPracticeListeners } from '@/modules/practice/listeners';
import { registerPracticeClientIntakesListeners } from '@/modules/practice-client-intakes/listeners';
import { registerPreferencesListeners } from '@/modules/preferences/listeners';
import { registerStripeListeners } from '@/modules/stripe/listeners';
import { registerSystemListeners } from '@/shared/events/listeners/system.listeners';

const logger = getLogger(['events', 'bootstrap']);

/**
 * Bootstrap all event listeners
 */
export async function bootstrapEventListeners(): Promise<void> {
  logger.info('Bootstrapping event listeners...');

  // analytics listeners
  registerAnalyticsListeners();

  // auth listeners
  registerAuthListeners();

  // clients listeners
  registerClientsListeners();

  // matters listeners
  registerMattersListeners();

  // onboarding listeners
  registerOnboardingListeners();

  // practice listeners
  registerPracticeListeners();

  // practice-client-intakes listeners
  registerPracticeClientIntakesListeners();

  // preferences listeners
  registerPreferencesListeners();

  // stripe listeners
  registerStripeListeners();

  // system listeners
  registerSystemListeners();

  logger.info('All event listeners bootstrapped successfully');
}
