#!/usr/bin/env tsx
/// <reference types="node" />
/**
 * Codegen Script
 * Runs all code-generation steps (module registry, config registry, schema sync, listener sync).
 * Used in CI to validate correctness without the full production build (tsup + tsc-alias).
 */

import { spawn } from 'node:child_process';
import { existsSync } from 'node:fs';
import { readdir, readFile, writeFile } from 'node:fs/promises';
import { join } from 'node:path';

const isDevelopment = (): boolean => (process.env.APP_ENV?.toLowerCase() ?? 'development') === 'development';

const spawnAsync = (cmd: string): Promise<void> =>
  new Promise((resolve, reject) => {
    const child = spawn(cmd, [], { stdio: 'inherit', shell: true });
    child.on('close', (code) => {
      if (code === 0) {
        resolve();
      } else {
        reject(new Error(`"${cmd}" exited with code ${String(code)}`));
      }
    });
    child.on('error', reject);
  });

const MODULES_DIR = join(process.cwd(), 'src/modules');
const MODULE_REGISTRY_OUTPUT = join(process.cwd(), 'src/shared/router/modules.generated.ts');
const MCP_TOOLS_OUTPUT = join(process.cwd(), 'src/modules/mcp/mcp.tools.generated.ts');
const UOW_OUTPUT = join(process.cwd(), 'src/shared/database/uow.generated.ts');

const EXCLUDED_MODULES = ['auth', 'analytics', 'billing', 'admin', 'customers', 'events', 'health', 'mcp', 'settings'];

if (!isDevelopment()) {
  EXCLUDED_MODULES.push('dev');
}

const toCamelCase = (str: string): string => str.replace(/-([a-z])/g, (_, letter) => letter.toUpperCase());

const toIdentifier = (str: string): string => toCamelCase(str.replace(/[^a-zA-Z0-9]+(.)?/g, (_, letter) => (letter ? letter.toUpperCase() : '')));

const discoverModules = async (): Promise<string[]> => {
  const allDirs = await readdir(MODULES_DIR, { withFileTypes: true });
  return allDirs
    .filter((dir) => dir.isDirectory())
    .map((dir) => dir.name)
    .filter((name) => !EXCLUDED_MODULES.includes(name) && !name.startsWith('.'))
    .sort();
};

const generateModuleRegistry = async (modules: string[]): Promise<void> => {
  const imports: string[] = [];
  const registryEntries: string[] = [];

  for (const mod of modules) {
    const httpPath = join(MODULES_DIR, mod, 'http.ts');
    const httpText = await readFile(httpPath, 'utf-8');
    const varName = toCamelCase(mod);
    const mountVarName = `${varName}MountPath`;
    const hasMountPathExport = /\bexport\s+const\s+mountPath\b/.test(httpText);

    imports.push(
      hasMountPathExport
        ? `import ${varName}Http, { mountPath as ${mountVarName} } from '@/modules/${mod}/http';`
        : `import ${varName}Http from '@/modules/${mod}/http';`
    );
    registryEntries.push(
      `  { name: '${mod}', http: ${varName}Http, mountPath: ${hasMountPathExport ? mountVarName : `'/api/${mod}'`} }`
    );
  }

  const content = `// 🤖 AUTO-GENERATED - DO NOT EDIT\n// Generated by: scripts/codegen.ts\n\n${imports.join('\n')}\n\nexport const MODULE_REGISTRY = [\n${registryEntries.join(',\n')}\n] as const;\n\nexport type ModuleName = typeof MODULE_REGISTRY[number]['name'];\n`;

  await writeFile(MODULE_REGISTRY_OUTPUT, content, 'utf-8');
  console.log('✅ Generated: src/shared/router/modules.generated.ts');
};

const generateMcpToolsRegistry = async (modules: string[]): Promise<void> => {
  const mcpImports: string[] = [];
  const mcpSpreads: string[] = [];

  for (const mod of modules) {
    const routesDir = join(MODULES_DIR, mod, 'routes');
    const routesIndexPath = join(MODULES_DIR, mod, 'routes', 'index.ts');
    const routesFlatPath = join(MODULES_DIR, mod, 'routes.ts');
    const routeModules: string[] = [];

    if (existsSync(routesIndexPath)) {
      const routeFiles = (await readdir(routesDir)).filter((f) => f.endsWith('.ts'));
      const hasMcp = (
        await Promise.all(routeFiles.map((file) => readFile(join(routesDir, file), 'utf-8')))
      ).some((text) => text.includes('mcp:'));
      if (hasMcp) {
        routeModules.push('routes/index');
      }
    } else if (existsSync(routesDir)) {
      const routeFiles = (await readdir(routesDir)).filter((f) => f.endsWith('.ts'));
      for (const file of routeFiles) {
        const text = await readFile(join(routesDir, file), 'utf-8');
        if (text.includes('mcp:')) {
          routeModules.push(`routes/${file.replace(/\.ts$/, '')}`);
        }
      }
    } else if (existsSync(routesFlatPath)) {
      const text = await readFile(routesFlatPath, 'utf-8');
      if (text.includes('mcp:')) {
        routeModules.push('routes');
      }
    }

    const moduleFiles = (await readdir(join(MODULES_DIR, mod))).filter(
      (file) => file.endsWith('.routes.ts') && file !== 'routes.ts'
    );
    for (const file of moduleFiles) {
      const text = await readFile(join(MODULES_DIR, mod, file), 'utf-8');
      if (text.includes('mcp:')) {
        routeModules.push(file.replace(/\.ts$/, ''));
      }
    }

    routeModules.forEach((routesRelPath, index) => {
      const varName = `${toIdentifier(mod)}Routes${index === 0 ? '' : String(index + 1)}`;
      mcpImports.push(`import * as ${varName} from '@/modules/${mod}/${routesRelPath}';`);
      mcpSpreads.push(`  ...buildMcpToolsFromModule(${varName}),`);
    });
  }

  const header = `// 🤖 AUTO-GENERATED - DO NOT EDIT\n// Generated by: scripts/codegen.ts\n`;
  const imports = [
    `import type { AnyToolDef } from '@/modules/mcp/types';`,
    `import { buildMcpToolsFromModule } from '@/modules/mcp/tool-registry';`,
    ...mcpImports,
  ].join('\n');

  const registry = `\nexport const MCP_TOOLS_REGISTRY: AnyToolDef[] = [\n${mcpSpreads.join('\n')}\n];\n`;
  const content = `${header}\n${imports}\n${registry}`;

  await writeFile(MCP_TOOLS_OUTPUT, content, 'utf-8');
  console.log('✅ Generated: src/modules/mcp/mcp.tools.generated.ts');
};

const generateUowRegistry = async (): Promise<void> => {
  const content = `// 🤖 AUTO-GENERATED - DO NOT EDIT\n// Generated by: scripts/codegen.ts\n\nexport interface UowRepositories {}\n\nexport const buildUowRepositories = (): UowRepositories => ({});\n`;

  await writeFile(UOW_OUTPUT, content, 'utf-8');
  console.log('✅ Generated: src/shared/database/uow.generated.ts');
};

const main = async (): Promise<void> => {
  console.log('\n⚡ Codegen (parallel)');
  console.log('─'.repeat(50));

  try {
    const modules = await discoverModules();
    console.log(`✅ Discovered ${modules.length} modules`);

    const results = await Promise.allSettled([
      generateModuleRegistry(modules),
      generateMcpToolsRegistry(modules),
      generateUowRegistry(),
      spawnAsync('tsx scripts/sync-schemas.ts'),
      spawnAsync('tsx scripts/sync-listeners.ts'),
    ]);

    const failures = results.filter((r): r is PromiseRejectedResult => r.status === 'rejected');
    if (failures.length > 0) {
      const messages = failures.map((f) => (f.reason instanceof Error ? f.reason.message : String(f.reason)));
      throw new Error(`Codegen failed:\n${messages.join('\n')}`);
    }

    console.log('\n✅ All codegen steps completed\n');
  } catch (error) {
    console.error('\n❌ Codegen failed:', error);
    process.exit(1);
  }
};

void main();
