#!/usr/bin/env tsx
/// <reference types="node" />
/**
 * Codegen Script
 * Runs all code-generation steps (module registry, config registry, schema sync, listener sync).
 * Used in CI to validate correctness without the full production build (tsup + tsc-alias).
 */

import { spawn } from 'node:child_process';
import { existsSync } from 'node:fs';
import { readdir, readFile, writeFile } from 'node:fs/promises';
import { join } from 'node:path';

const isDevelopment = (): boolean => (process.env.APP_ENV?.toLowerCase() ?? 'development') === 'development';

const spawnAsync = (cmd: string): Promise<void> =>
  new Promise((resolve, reject) => {
    const child = spawn(cmd, [], { stdio: 'inherit', shell: true });
    child.on('close', (code) => {
      if (code === 0) {
        resolve();
      } else {
        reject(new Error(`"${cmd}" exited with code ${String(code)}`));
      }
    });
    child.on('error', reject);
  });

const MODULES_DIR = join(process.cwd(), 'src/modules');
const SHARED_REPOS_DIR = join(process.cwd(), 'src/shared/repositories');
const MODULE_REGISTRY_OUTPUT = join(process.cwd(), 'src/shared/router/modules.generated.ts');
const CONFIG_REGISTRY_OUTPUT = join(process.cwd(), 'src/shared/router/configs.generated.ts');
const MCP_TOOLS_OUTPUT = join(process.cwd(), 'src/modules/mcp/mcp.tools.generated.ts');
const UOW_REGISTRY_OUTPUT = join(process.cwd(), 'src/shared/database/uow.generated.ts');

const EXCLUDED_MODULES = ['auth', 'analytics', 'billing', 'admin', 'customers', 'events', 'health', 'mcp', 'settings'];

if (!isDevelopment()) {
  EXCLUDED_MODULES.push('dev');
}

const toCamelCase = (str: string): string => str.replace(/-([a-z])/g, (_, letter) => letter.toUpperCase());

const discoverModules = async (): Promise<string[]> => {
  const allDirs = await readdir(MODULES_DIR, { withFileTypes: true });
  return allDirs
    .filter((dir) => dir.isDirectory())
    .map((dir) => dir.name)
    .filter((name) => !EXCLUDED_MODULES.includes(name) && !name.startsWith('.'))
    .sort();
};

const generateModuleRegistry = async (modules: string[]): Promise<void> => {
  const imports = modules.map((mod) => `import ${toCamelCase(mod)}Http from '@/modules/${mod}/http';`).join('\n');
  const registryEntries = modules.map((mod) => `  { name: '${mod}', http: ${toCamelCase(mod)}Http }`).join(',\n');

  const content = `// 🤖 AUTO-GENERATED - DO NOT EDIT\n// Generated by: scripts/codegen.ts\n\n${imports}\n\nexport const MODULE_REGISTRY = [\n${registryEntries}\n] as const;\n\nexport type ModuleName = typeof MODULE_REGISTRY[number]['name'];\n`;

  await writeFile(MODULE_REGISTRY_OUTPUT, content, 'utf-8');
  console.log('✅ Generated: src/shared/router/modules.generated.ts');
};

const generateConfigRegistry = async (modules: string[]): Promise<void> => {
  const configImports: string[] = [];
  const configEntries: string[] = [];

  for (const mod of modules) {
    const configPath = join(MODULES_DIR, mod, 'routes.config.ts');
    if (existsSync(configPath)) {
      const configVar = `${toCamelCase(mod)}Config`;
      configImports.push(`import { config as ${configVar} } from '@/modules/${mod}/routes.config';`);
      configEntries.push(`  { name: '${mod}', config: ${configVar} }`);
    } else {
      configEntries.push(`  { name: '${mod}', config: undefined }`);
    }
  }

  const content = `// 🤖 AUTO-GENERATED - DO NOT EDIT\n// Generated by: scripts/codegen.ts\n\n${configImports.join('\n')}\n\nexport const CONFIG_REGISTRY = [\n${configEntries.join(',\n')}\n] as const;\n`;

  await writeFile(CONFIG_REGISTRY_OUTPUT, content, 'utf-8');
  console.log('✅ Generated: src/shared/router/configs.generated.ts');
};

/**
 * Modules that have been migrated to use getActiveTx (UoW pattern).
 * Add module name here once its repository file uses getActiveTx.
 */
const UOW_MIGRATED_MODULES = [
  'practice-client-intakes',
  // 'engagement-contracts',  // ← add as each module is migrated
  // 'clients',
  // 'matters',
];

const generateUowRegistry = async (): Promise<void> => {
  const imports: string[] = [];
  const entries: string[] = [];

  for (const mod of UOW_MIGRATED_MODULES) {
    const queriesDir = join(MODULES_DIR, mod, 'database/queries');
    if (!existsSync(queriesDir)) {
      console.warn(`⚠️  UoW: no queries dir for module '${mod}' — skipping`);
      continue;
    }

    const files = (await readdir(queriesDir)).filter((f) => f.endsWith('.ts'));
    for (const file of files) {
      const content = await readFile(join(queriesDir, file), 'utf-8');
      if (!content.includes("from '@/shared/database/uow'")) continue;

      // Find the exported object name: `export const xyzRepository = {`
      const exportMatch = content.match(/export const (\w+)\s*=/);
      if (!exportMatch) continue;
      const exportName = exportMatch[1];

      const propName = toCamelCase(mod);
      const importPath = `@/modules/${mod}/database/queries/${file.replace('.ts', '')}`;

      imports.push(`import { ${exportName} } from '${importPath}';`);
      entries.push(`  ${propName}: ${exportName},`);
    }
  }

  const header = `// 🤖 AUTO-GENERATED - DO NOT EDIT\n// Generated by: scripts/codegen.ts\n// Add migrated modules to UOW_MIGRATED_MODULES in codegen.ts\n`;
  const body =
    entries.length > 0
      ? `\n${imports.join('\n')}\n\nexport const generatedRepositories = {\n${entries.join('\n')}\n};\n`
      : `\nexport const generatedRepositories = {};\n`;

  await writeFile(UOW_REGISTRY_OUTPUT, header + body, 'utf-8');
  console.log(`✅ Generated: src/shared/database/uow.generated.ts (${entries.length} repos)`);
};

const generateMcpToolsRegistry = async (modules: string[]): Promise<void> => {
  const mcpImports: string[] = [];
  const mcpSpreads: string[] = [];

  for (const mod of modules) {
    const routesIndexPath = join(MODULES_DIR, mod, 'routes', 'index.ts');
    const routesFlatPath = join(MODULES_DIR, mod, 'routes.ts');

    let routesRelPath: string | null = null;
    if (existsSync(routesIndexPath)) {
      routesRelPath = 'routes/index';
    } else if (existsSync(routesFlatPath)) {
      routesRelPath = 'routes';
    }

    if (!routesRelPath) continue;

    // For directory-style modules (routes/index.ts), scan all *.ts files in the routes/ dir
    let hasMcp = false;
    if (routesRelPath === 'routes/index') {
      const routesDir = join(MODULES_DIR, mod, 'routes');
      const routeFiles = (await readdir(routesDir)).filter((f) => f.endsWith('.ts'));
      for (const file of routeFiles) {
        const text = await readFile(join(routesDir, file), 'utf-8');
        if (text.includes('mcp:')) {
          hasMcp = true;
          break;
        }
      }
    } else {
      const text = await readFile(routesFlatPath, 'utf-8');
      hasMcp = text.includes('mcp:');
    }
    if (!hasMcp) continue;

    const varName = `${toCamelCase(mod)}Routes`;
    mcpImports.push(`import * as ${varName} from '@/modules/${mod}/${routesRelPath}';`);
    mcpSpreads.push(`  ...buildMcpToolsFromModule(${varName}),`);
  }

  const header = `// 🤖 AUTO-GENERATED - DO NOT EDIT\n// Generated by: scripts/codegen.ts\n`;
  const imports = [
    `import type { AnyToolDef } from '@/modules/mcp/types';`,
    `import { buildMcpToolsFromModule } from '@/modules/mcp/tool-registry';`,
    ...mcpImports,
  ].join('\n');

  const registry = `\nexport const MCP_TOOLS_REGISTRY: AnyToolDef[] = [\n${mcpSpreads.join('\n')}\n];\n`;
  const content = `${header}\n${imports}\n${registry}`;

  await writeFile(MCP_TOOLS_OUTPUT, content, 'utf-8');
  console.log('✅ Generated: src/modules/mcp/mcp.tools.generated.ts');
};

const main = async (): Promise<void> => {
  console.log('\n⚡ Codegen (parallel)');
  console.log('─'.repeat(50));

  try {
    const modules = await discoverModules();
    console.log(`✅ Discovered ${modules.length} modules`);

    const results = await Promise.allSettled([
      generateModuleRegistry(modules),
      generateConfigRegistry(modules),
      generateMcpToolsRegistry(modules),
      generateUowRegistry(),
      spawnAsync('tsx scripts/sync-schemas.ts'),
      spawnAsync('tsx scripts/sync-listeners.ts'),
    ]);

    const failures = results.filter((r): r is PromiseRejectedResult => r.status === 'rejected');
    if (failures.length > 0) {
      const messages = failures.map((f) => (f.reason instanceof Error ? f.reason.message : String(f.reason)));
      throw new Error(`Codegen failed:\n${messages.join('\n')}`);
    }

    console.log('\n✅ All codegen steps completed\n');
  } catch (error) {
    console.error('\n❌ Codegen failed:', error);
    process.exit(1);
  }
};

void main();
