import { readdirSync, statSync, writeFileSync, existsSync } from 'fs';
import { join, relative } from 'path';

const MODULES_DIR = join(process.cwd(), 'src/modules');
const SHARED_EVENTS_DIR = join(process.cwd(), 'src/shared/events');
const LISTENERS_DIR = join(process.cwd(), 'src/shared/events/listeners');
const BOOTSTRAP_FILE = join(process.cwd(), 'src/shared/events/bootstrap.ts');

const toCamelCase = (str: string) => str.replace(/[-/.]([a-z])/g, (_, letter) => letter.toUpperCase());

const getRegistrationFunction = (modName: string) => {
  const camelName = toCamelCase(modName);
  // Remove 'index' from the end of function name if it exists (e.g., system.listeners -> registerSystemListeners)
  const baseName = camelName.endsWith('Listeners') ? camelName : `${camelName}Listeners`;
  return `register${baseName.charAt(0).toUpperCase()}${baseName.slice(1)}`;
};

const findListeners = (): { moduleName: string; importPath: string; functionName: string }[] => {
  const registrations: { moduleName: string; importPath: string; functionName: string }[] = [];

  // 1. Scan src/modules/*/listeners.ts
  if (existsSync(MODULES_DIR)) {
    const modules = readdirSync(MODULES_DIR);
    for (const mod of modules) {
      const modPath = join(MODULES_DIR, mod);
      if (statSync(modPath).isDirectory()) {
        const listenersPath = join(modPath, 'listeners.ts');
        if (existsSync(listenersPath)) {
          registrations.push({
            moduleName: mod,
            importPath: `@/modules/${mod}/listeners`,
            functionName: getRegistrationFunction(mod),
          });
        }
      }
    }
  }

  // 2. Scan src/shared/events/listeners/*.listeners.ts
  if (existsSync(LISTENERS_DIR)) {
    const items = readdirSync(LISTENERS_DIR);
    for (const item of items) {
      const fullPath = join(LISTENERS_DIR, item);
      if (statSync(fullPath).isFile() && item.endsWith('.listeners.ts')) {
        const name = item.replace('.listeners.ts', '');
        registrations.push({
          moduleName: name,
          importPath: `@/shared/events/listeners/${name}.listeners`,
          functionName: getRegistrationFunction(name),
        });
      }
    }
  }

  return registrations;
};

const generateBootstrap = () => {
  console.log('🔍 Scanning for event listeners...');

  const regs = findListeners().sort((a, b) => a.moduleName.localeCompare(b.moduleName));

  const content = `/**
 * AUTO-GENERATED FILE - DO NOT EDIT MANUALLY
 *
 * This file is automatically generated by: pnpm run sync:listeners
 * It imports and registers all event listeners discovered in modules and shared directories.
 *
 * To add a new listener:
 * 1. Create a listeners.ts file in your module or a *.listeners.ts in shared/events/listeners
 * 2. Export a function named register{ModuleName}Listeners()
 * 3. Run: pnpm run sync:listeners (or pnpm run build)
 *
 * Last updated: ${new Date().toISOString()}
 */

import { getLogger } from '@logtape/logtape';
${regs.map(r => `import { ${r.functionName} } from '${r.importPath}';`).join('\n')}

const logger = getLogger(['events', 'bootstrap']);

/**
 * Bootstrap all event listeners
 */
export async function bootstrapEventListeners(): Promise<void> {
  logger.info('Bootstrapping event listeners...');

${regs.map(r => `  // ${r.moduleName} listeners\n  ${r.functionName}();`).join('\n\n')}

  logger.info('All event listeners bootstrapped successfully');
}
`;

  writeFileSync(BOOTSTRAP_FILE, content, 'utf-8');
  console.log('✅ Event bootstrap file generated successfully!');
  console.log(`   📦 ${regs.length} listener registrations added`);

  regs.forEach(r => {
    console.log(`   • ${r.moduleName} -> ${r.functionName}`);
  });
};

try {
  generateBootstrap();
} catch (error) {
  console.error('❌ Failed to generate event bootstrap:', error);
  process.exit(1);
}
