/**
 * AUTO-GENERATED FILE - DO NOT EDIT MANUALLY
 *
 * This file is automatically generated by: pnpm run sync:schemas
 * It exports all schema TABLE and RELATIONS files from modules and shared directories.
 *
 * Tables are exported before relations to avoid ESM initialization order issues.
 *
 * To add a new schema or relations file:
 * 1. Create a new *.schema.ts (table) or *-relations.schema.ts (relations) file
 * 2. Run: pnpm run sync:schemas
 *
 * Last updated: 2026-06-02T12:31:56.030Z
 */

// Better Auth core schemas (users, sessions, organizations, etc.)
export * from './better-auth-schema';

// Auto-discovered schema TABLES from modules and shared directories
export * from './../modules/clients/database/schema/clients.schema';
export * from './../modules/clients/database/schema/practice-client-memos.schema';
export * from './../modules/engagement-contracts/database/schema/engagement-contracts.schema';
export * from './../modules/invoices/database/schema/billing-transactions.schema';
export * from './../modules/invoices/database/schema/invoice-line-items.schema';
export * from './../modules/invoices/database/schema/invoices.schema';
export * from './../modules/invoices/database/schema/payment-links.schema';
export * from './../modules/invoices/database/schema/refund-requests.schema';
export * from './../modules/matters/database/schema/matter-activity-log.schema';
export * from './../modules/matters/database/schema/matter-assignees.schema';
export * from './../modules/matters/database/schema/matter-deadlines.schema';
export * from './../modules/matters/database/schema/matter-expenses.schema';
export * from './../modules/matters/database/schema/matter-files.schema';
export * from './../modules/matters/database/schema/matter-milestones.schema';
export * from './../modules/matters/database/schema/matter-notes.schema';
export * from './../modules/matters/database/schema/matter-status-history.schema';
export * from './../modules/matters/database/schema/matter-tasks.schema';
export * from './../modules/matters/database/schema/matter-time-entries.schema';
export * from './../modules/matters/database/schema/matters.schema';
export * from './../modules/onboarding/schemas/onboarding.schema';
export * from './../modules/payouts/database/schema/payouts.schema';
export * from './../modules/practice-client-intakes/database/schema/practice-client-intakes.schema';
export * from './../modules/practice/database/schema/addresses.schema';
export * from './../modules/practice/database/schema/intake-templates.schema';
export * from './../modules/practice/database/schema/practice.schema';
export * from './../modules/preferences/schema/preferences.schema';
export * from './../modules/subscriptions/database/schema/stripe-prices.schema';
export * from './../modules/subscriptions/database/schema/subscription-events.schema';
export * from './../modules/subscriptions/database/schema/subscription-line-items.schema';
export * from './../modules/subscriptions/database/schema/subscriptions.schema';
export * from './../modules/trust/database/schema/trust-transactions.schema';
export * from './../shared/events/schemas/events-dead-letter.schema';
export * from './../shared/events/schemas/events.schema';
export * from './../shared/schemas/app-config.schema';
export * from './../shared/schemas/stripe.webhook-events.schema';
export * from './../shared/services/email/schemas/email-logs.schema';
export * from './../shared/uploads/schema/upload-audit-logs.schema';
export * from './../shared/uploads/schema/uploads.schema';
export * from './oauth.schema';

// Auto-discovered RELATIONS files — exported after tables to avoid TDZ issues
export * from './../modules/clients/database/schema/clients-relations.schema';
export * from './../modules/engagement-contracts/database/schema/engagement-contracts-relations.schema';
export * from './../modules/invoices/database/schema/billing-transactions-relations.schema';
export * from './../modules/invoices/database/schema/invoices-relations.schema';
export * from './../modules/matters/database/schema/matters-relations.schema';
export * from './../modules/payouts/database/schema/payouts-relations.schema';
export * from './../modules/subscriptions/database/schema/subscriptions-relations.schema';
export * from './better-auth-schema-relations';
export * from './subscription-relations.schema';

// Singular aliases required by @better-auth/drizzle-adapter — getSchema() uses exact model name (not usePlural)
export { oauthClients as oauthClient, oauthAccessTokens as oauthAccessToken, oauthRefreshTokens as oauthRefreshToken, oauthConsents as oauthConsent } from './oauth.schema';
